services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: sftpgo
      POSTGRES_USER: sftpgo
      POSTGRES_PASSWORD:
    volumes:
      - sftpdbdata:/var/lib/postgresql/data
  lb:
    build: .
    ports:
      - "22:22"
      - "8080:8080"
      - "70:70"
    expose:
      - "22"
      - "8080"
      - "70"
    links:
      - "sftpgo1"
      - "sftpgo2"
  sftpgo1:
    image: drakkan/sftpgo:latest
    expose:
      - "2022"
      - "8080"
    links:
      - "db"
    environment:
      SFTPGO_COMMON__PROXY_PROTOCOL: 1
      SFTPGO_DATA_PROVIDER__DRIVER: postgresql
      SFTPGO_DATA_PROVIDER__NAME: sftpgo
      SFTPGO_DATA_PROVIDER__HOST: db
      SFTPGO_DATA_PROVIDER__PORT: 5432
      SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
      SFTPGO_DATA_PROVIDER__PASSWORD:
      SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_CLIENT: "false"
    volumes:
      - sftpdata:/srv/sftpgo
      - sftphome:/var/lib/sftpgo
    depends_on:
      - "db"
  sftpgo2:
    image: drakkan/sftpgo:latest
    expose:
      - "2022"
      - "8080"
    links:
      - "db"
    environment:
      SFTPGO_COMMON__PROXY_PROTOCOL: 1
      SFTPGO_DATA_PROVIDER__DRIVER: postgresql
      SFTPGO_DATA_PROVIDER__NAME: sftpgo
      SFTPGO_DATA_PROVIDER__HOST: db
      SFTPGO_DATA_PROVIDER__PORT: 5432
      SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
      SFTPGO_DATA_PROVIDER__PASSWORD:
      SFTPGO_HTTPD__BINDINGS__0__ENABLE_WEB_CLIENT: "false"
    volumes:
      - sftpdata:/srv/sftpgo
      - sftphome:/var/lib/sftpgo
    depends_on:
      - "db"
volumes:
  sftpdata:
  sftphome:
  sftpdbdata:
